### ISSUE TITLE
Authentication Pages UI Improvements + Fixes

### ISSUE THREAD

**Issue by kevinboc** [kevinboc/yousuf-mobile-app#22]
- Fix the error messages in Register page
- Change title location (Login & Sign Up)
- Create a custom button
- Separate/distinguish the buttons
- Improve the popup error message
- MAYBE: Implement it with RiverPod provider for state management of the form (send API request only when everything is valid)

**Comment by Rha02** [comment]
Do PRs #24 and #29 resolve this issue?
